spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-demo-service

dubbo:
  application:
    name: spring-cloud-demo-service
  protocol:
    name: dubbo
    port: -1     #-1表示随机分配端口
  registry:
    address: nacos://192.168.112.1:8848  #我用nacos做注册中心
  scan:
    base-packages: com.qbccn.provider.demo.service  #dubbo扫描的包